version: '3.8'
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./temp/nginx:/var/log/nginx
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/envo:/etc/nginx/envo
      - ./services/nginx/sites-available:/etc/nginx/sites-available
      - ./services/nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "8080:8080"
    depends_on:
      - admin-api
  admin-api:
    build:
      context: ./
      dockerfile: ./services/admin/api/Dockerfile
      target: production
    volumes:
      - ./temp/admin/api:/temp/admin/api
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - LOGGING_LEVEL_CONSOLE=trace
      - LOGGING_LEVEL_STDOUT=trace
      - LOGGING_LEVEL_STDERR=warn
      - LOGGING_STDOUT_FILE=/temp/admin/api/stdout.log
      - LOGGING_STDERR_FILE=/temp/admin/api/stderr.log
      - DATABASE_URL=postgresql://postgres:envo@admin-db:5432/envo?schema=public
    ports:
      - 8081:8080
    depends_on:
      - admin-db
  admin-db:
    image: postgres:latest
    volumes:
      - ./temp/admin/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=envo
      - POSTGRES_PASSWORD=envo
    ports:
      - 5432:5432

