version: '3.8'
services:
  admin-db:
    image: postgres:latest
    volumes:
      - ./docker/.tmp/admin/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=envo
      - POSTGRES_PASSWORD=envo
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - ./docker/.tmp/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=envo@localhost.dev
      - PGADMIN_DEFAULT_PASSWORD=envo
    ports:
      - 9000:80
    logging:
      driver: none
