version: '3.8'
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./docker/.tmp/nginx:/var/log/nginx
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/envo:/etc/nginx/envo
      - ./services/nginx/ssl:/etc/nginx/ssl
      - ./services/nginx/sites-available:/etc/nginx/sites-available
      - ./services/nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "8080:8080"
      - "4443:4443"
    depends_on:
      - admin-api

  admin-db:
    image: postgres:latest
    volumes:
      - ./docker/.tmp/admin/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=envo
      - POSTGRES_PASSWORD=envo
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - ./docker/.tmp/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=envo@localhost.dev
      - PGADMIN_DEFAULT_PASSWORD=envo
    ports:
      - 9000:80
